# -*- coding: utf-8 -*-
"""Resume Parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnE--u0d8y1xc66qFeFhwmHYVOwhfuws
"""

import PyPDF2

import nltk

files = '/content/Fazil Resume.pdf'

pdfreader = PyPDF2.PdfReader(files)

page = pdfreader.getPage(0)
page1 = page.extractText()

page1

from nltk import word_tokenize

tokenized = word_tokenize(page1)

tokenized

#page11 = [x.replace('\n','') for x in tokenized]

import re

emails = re.findall(r"[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+", page1)

print(emails)

phone = re.findall(r'\d\d\d\d\d\d\d\d\d\d\d\d', page1)
if len(phone)<1:
  phone = re.findall(r'\d\d\d\d\d\d\d\d\d\d', page1)

print(phone)

new = page1[0:250]
new

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(new)

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

